<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="-0.025 0 ${wheel_radius+0.187}" rpy="0 3.14159265359 1.57079"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <origin xyz="0.0025 0 0.045" rpy=" -1.57079  0   3.14159265359"/>
            <geometry>
                <mesh filename="package://robot_descriptor/meshes/lidar.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="black"/>
        </visual>

        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>



    <gazebo reference="laser_frame">
    <material>Gazebo/Black</material>
    <self_collide>false</self_collide>

    <sensor name="ld06" type="gpu_lidar">
        <pose>0 0 0 0 0 0</pose>
        <always_on>true</always_on>
        <update_rate>10</update_rate>
        <visualize>false</visualize>
        <topic>scan</topic>
        <ignition_frame_id>laser_frame</ignition_frame_id>
        <lidar>

        <scan>
            <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.141592</min_angle>
            <max_angle>3.141592</max_angle>
            </horizontal>
        </scan>

        <range>
            <min>0.1</min>
            <max>12.0</max>
            <resolution>0.01</resolution>
        </range>

        <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.02</stddev>
        </noise>

        </lidar>

    </sensor>
    </gazebo>

</robot>
